import pandas as pd
orders = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\orders.csv')
aisles = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\aisles.csv')
products = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\products.csv')
departments = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\departments.csv')
order_products__train = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\order_products__train.csv')
order_products__prior = pd.read_csv(r'C:\Users\Madhumathi\Desktop\RetailPulse\01_Data\order_products__prior.csv')

for name, df in [('orders', orders), ('aisles', aisles), ('products', products), ('departments', departments), ('order_products__train', order_products__train), ('order_products__prior', order_products__prior)]:
    print(f'\n--- {name}---')
    print(df.shape)
    print(df.head())
    print(df.isnull().sum())
orders['days_since_prior_order'] = orders['days_since_prior_order'].fillna(0)
print(orders['days_since_prior_order'].isnull().sum())
orders_products = pd.merge(order_products__prior,orders, on='order_id', how='left')
print(orders_products.shape)
print(orders_products.head())
products_full = pd.merge(products, aisles, on='aisle_id', how='left')
products_full = pd.merge(products_full, departments, on='department_id',how='left')
final_data = pd.merge(orders_products, products_full, on='product_id', how='left')
print(final_data.shape)
print(final_data.head())
print(final_data.columns)
final_data['reorder_rate'] = final_data.groupby('product_id')['reordered'].transform('mean')
final_data.to_csv(r'C:\Users\Madhumathi\Desktop\Retailpulse\01_Data\Cleaned_data.csv', index=False)